on:
  push:
    branches:
    - main

jobs:
  my_job:
    name: deploy to production
    runs-on: BackendDeployment
    steps:
    - run: git pull
    - run: dotnet run -e ASPNETCORE_ENVIRONMENT=development

